version: '3.8'
services:
  
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://s:uoflviFmf9OFNsc8@cluster0.iv4v7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
volumes:
  mongo-data:
